export const Suralist = 
 [
{ "num" :1,"EngName":"al-Fatihah","arabicName":"al-faatiHah","engTranlated":"The Opening"},
{ "num" :  2, "EngName":"al-Baqarah","arabicName":"al-baqarah","engTranlated":"The Cow"},
{ "num" :  3, "EngName":"Al-Imran","arabicName":"aali- imraan","engTranlated":"The Family Of Imran"},
{ "num" :  4, "EngName":"an-Nisa","arabicName":"an-nisaa","engTranlated":"Women"},
{ "num" :  5, "EngName":"al-Maidah","arabicName":"al-maaidah","engTranlated":"The Food"},
{ "num" :  6, "EngName":"al-An am","arabicName":"al-an aam","engTranlated":"The Cattle"},
{ "num" :  7, "EngName":"al-A raf","arabicName":"al-a raaf","engTranlated":"The Elevated Places"},
{ "num" :  8, "EngName":"al-Anfal","arabicName":"al-anfaal","engTranlated":"The Spoils Of War"},
{ "num" :  9, "EngName":"at-Taubah","arabicName":"at-tawbah","engTranlated":"Repentance"},
{ "num" :  10, "EngName":"Yunus","arabicName":"yoonus","engTranlated":"Jonah"},
{ "num" :  11, "EngName":"Hud","arabicName":"hood","engTranlated":"Hud"},
{ "num" :  12, "EngName":"Yusuf","arabicName":"yoosuf","engTranlated":"Joseph"},
{ "num" :  13, "EngName":"ar-Ra d","arabicName":"ar-Ra d","engTranlated":"The Thunder"},
{ "num" :  14, "EngName":"Ibrahim","arabicName":"ibraheem","engTranlated":"Abraham"},
{ "num" :  15, "EngName":"al-Hijr","arabicName":"al-Hijr","engTranlated":"The Rock"},
{ "num" :  16, "EngName":"an-Nahl","arabicName":"an-naHl","engTranlated":"The Bee"},
{ "num" :  17, "EngName":"Al-Isra","arabicName":"al-Isra","engTranlated":"The Night Journey"},
{ "num" :  18, "EngName":"al-Kahf","arabicName":"al-kahf","engTranlated":"The Cave"},
{ "num" :  19, "EngName":"Maryam","arabicName":"maryam","engTranlated":"Mary"},
{ "num" :  20, "EngName":"Ta Ha","arabicName":"Taa haa","engTranlated":"Ta Ha"},
{ "num" :  21, "EngName":"al-Anbiya","arabicName":"al-anbiyaa","engTranlated":"The Prophets"},
{ "num" :  22, "EngName":"al-Hajj","arabicName":"al-Hajj","engTranlated":"The Pilgrimage"},
{ "num" :  23, "EngName":"al-Muminun","arabicName":"al-muminoon","engTranlated":"The Believers"},
{ "num" :  24, "EngName":"an-Nur","arabicName":"an-noor","engTranlated":"The Light"},
{ "num" :  25, "EngName":"al-Furqan","arabicName":"al-furqaan","engTranlated":"The Criterion"},
{ "num" :  26, "EngName":"ash-Shu ara","arabicName":"ash-shu araa","engTranlated":"The Poets"},
{ "num" :  27, "EngName":"an-Naml","arabicName":"an-naml","engTranlated":"The Ant"},
{ "num" :  28, "EngName":"al-Qasas","arabicName":"al-qasas","engTranlated":"The Narrative"},
{ "num" :  29, "EngName":"al- Ankabut","arabicName":"al- ankaboot","engTranlated":"The Spider"},
{ "num" :  30, "EngName":"ar-Rum","arabicName":"ar-room","engTranlated":"The Romans"},
{ "num" :  31, "EngName":"Luqman","arabicName":"luqmaan","engTranlated":"Lukman"},
{ "num" :  32, "EngName":"as-Sajdah","arabicName":"as-sajdah","engTranlated":"The Adoration"},
{ "num" :  33, "EngName":"al-Ahzab","arabicName":"al-aHzab","engTranlated":"The Allies"},
{ "num" :  34, "EngName":"Saba","arabicName":"as-Saba","engTranlated":"Sheba"},
{ "num" :  35, "EngName":"Fatir","arabicName":"faaTir","engTranlated":"The Creator"},
{ "num" :  36, "EngName":"Ya Sin","arabicName":"yaa seen","engTranlated":"Ya Sin"},
{ "num" :  37, "EngName":"as-Saffat","arabicName":"aS-Saaffaat","engTranlated":"The Rangers"},
{ "num" :  38, "EngName":"Sad","arabicName":"Saad","engTranlated":"Sad"},
{ "num" :  39, "EngName":"az-Zumar","arabicName":"az-zumar","engTranlated":"The Companies"},
{ "num" :  40, "EngName":"Ghafir","arabicName":"Ghafir","engTranlated":"The Forgiving One"},
{ "num" :  41, "EngName":"Fussilat","arabicName":"Fussilat","engTranlated":"Revelations Well Expounded"},
{ "num" :  42, "EngName":"ash-Shura","arabicName":"ash-shooraa","engTranlated":"The Counsel"},
{ "num" :  43, "EngName":"az-Zukhruf","arabicName":"azl-zukhruf","engTranlated":"The Embellishment"},
{ "num" :  44, "EngName":"ad-Dukhan","arabicName":"ad-dukhaan","engTranlated":"The Evident Smoke"},
{ "num" :  45, "EngName":"al-Jathiyah","arabicName":"al-jaathiyah","engTranlated":"The Kneeling"},
{ "num" :  46, "EngName":"al-Ahqaf","arabicName":"al-aHqaaf","engTranlated":"The Sandhills"},
{ "num" :  47, "EngName":"Muhammad","arabicName":"muHammad","engTranlated":"Muhammad"},
{ "num" :  48, "EngName":"al-Fath","arabicName":"al-fatH","engTranlated":"The Victory"},
{ "num" :  49, "EngName":"al-Hujurat","arabicName":"al-Hujuraat","engTranlated":"The Chambers"},
{ "num" :  50, "EngName":"Qaf","arabicName":"qaaf","engTranlated":"Qaf"},
{ "num" :  51, "EngName":"ad-Dhariyat","arabicName":"ad-dhaariyaat","engTranlated":"The Scatterers"},
{ "num" :  52, "EngName":"at-Tur","arabicName":"aT-Toor","engTranlated":"The Mountain"},
{ "num" :  53, "EngName":"an-Najm","arabicName":"an-najm","engTranlated":"The Star"},
{ "num" :  54, "EngName":"al-Qamar","arabicName":"al-qamar","engTranlated":"The Moon"},
{ "num" :  55, "EngName":"ar-Rahman","arabicName":"ar-raHmaan","engTranlated":"The Merciful"},
{ "num" :  56, "EngName":"al-Waqi ah","arabicName":"al-waaqi ah","engTranlated":"That Which is Coming"},
{ "num" :  57, "EngName":"al-Hadid","arabicName":"al-Hadeed","engTranlated":"The Iron"},
{ "num" :  58, "EngName":"al-Mujadilah","arabicName":"al-mujaadilah","engTranlated":"She Who Pleaded"},
{ "num" :  59, "EngName":"al-Hashr","arabicName":"al-Hashr","engTranlated":"The Exile"},
{ "num" :  60, "EngName":"al-Mumtahanah","arabicName":"al-mumtaHanah","engTranlated":"She Who is Tested"},
{ "num" :  61, "EngName":"as-Saff","arabicName":"as-saff","engTranlated":"The Ranks"},
{ "num" :  62, "EngName":"al-Jumu ah","arabicName":"al-jumu ah","engTranlated":"The Day of Congregation"},
{ "num" :  63, "EngName":"al-Munafiqun","arabicName":"al-munafiqoon","engTranlated":"The Hypocrites"},
{ "num" :  64, "EngName":"at-Taghabun","arabicName":"at-taghaabun","engTranlated":"The Cheating"},
{ "num" :  65, "EngName":"at-Talaq,","arabicName":"aT-Talaaq","engTranlated":"The Divorce"},
{ "num" :  66, "EngName":"at-Tahrim","arabicName":"at-taHreem","engTranlated":"The Prohibition"},
{ "num" :  67, "EngName":"al-Mulk","arabicName":"al-mulk","engTranlated":"The Kingdom"},
{ "num" :  68, "EngName":"al-Qalam","arabicName":"al-qalam","engTranlated":"The Pen"},
{ "num" :  69, "EngName":"al-Haqqah","arabicName":"al-Haaqqah","engTranlated":"The Inevitable"},
{ "num" :  70, "EngName":"al-Ma arij","arabicName":"al-ma aarij","engTranlated":"The Ladders"},
{ "num" :  71, "EngName":"Nuh","arabicName":"nooH","engTranlated":"Noah"},
{ "num" :  72, "EngName":"al-Jinn","arabicName":"al-jinn","engTranlated":"The Jinn"},
{ "num" :  73, "EngName":"al-Muzammil","arabicName":"al-muzammil","engTranlated":"The Mantled One"},
{ "num" :  74, "EngName":"al-Mudathir","arabicName":"al-muddaththir","engTranlated":"The Clothed One"},
{ "num" :  75, "EngName":"al-Qiyamah","arabicName":"al-qiyaamah","engTranlated":"The Resurrection"},
{ "num" :  76, "EngName":"al-Insane","arabicName":"al-insane","engTranlated":"The Man"},
{ "num" :  77, "EngName":"al-Mursalat","arabicName":"al-mursalaat","engTranlated":"The Emissaries"},
{ "num" :  78, "EngName":"an-Naba","arabicName":"an-naba","engTranlated":"The Tidings"},
{ "num" :  79, "EngName":"an-Nazi at","arabicName":"an-naazi aat","engTranlated":"Those Who Pull Out"},
{ "num" :  80, "EngName":" Abasa","arabicName":" abasa","engTranlated":"He Frowned"},
{ "num" :  81, "EngName":"at-Takwir","arabicName":"at-takweer","engTranlated":"The Cessation"},
{ "num" :  82, "EngName":"al-Infitar","arabicName":"al-infiTaar","engTranlated":"The Cleaving Asunder"},
{ "num" :  83, "EngName":"Al-Mutaffifeen","arabicName":"Al-Mutaffifeen","engTranlated":"The Defrauders"},
{ "num" :  84, "EngName":"al-Inshiqaq","arabicName":"al-inshiqaaq","engTranlated":"The Rending"},
{ "num" :  85, "EngName":"al-Buruj","arabicName":"al-burooj","engTranlated":"the Constellations"},
{ "num" :  86, "EngName":"at-Tariq","arabicName":"aT-Taariq","engTranlated":"The Night-Comer"},
{ "num" :  87, "EngName":"al-A la","arabicName":"al-A laa","engTranlated":"The Most High"},
{ "num" :  88, "EngName":"al-Ghashiya","arabicName":"al-ghaashiyah","engTranlated":"The Overwhelming Calamity"},
{ "num" :  89, "EngName":"al-Fajr","arabicName":"al-fajr","engTranlated":"The Dawn"},
{ "num" :  90, "EngName":"al-Balad","arabicName":"al-balad","engTranlated":"The City"},
{ "num" :  91, "EngName":"ash-Shams","arabicName":"ash-shams","engTranlated":"The Sun"},
{ "num" :  92, "EngName":"al-Layl","arabicName":"al-lail","engTranlated":"The Night"},
{ "num" :  93, "EngName":"ad-Duha","arabicName":"aD-DuHaa","engTranlated":"The Early Hours"},
{ "num" :  94, "EngName":"ash-Sharh","arabicName":"ash-Sharh","engTranlated":"The Expansion"},
{ "num" :  95, "EngName":"at-Tin","arabicName":"aT-Teen","engTranlated":"The Fig"},
{ "num" :  96, "EngName":"al- Alaq","arabicName":"al- alaq","engTranlated":"The Clot"},
{ "num" :  97, "EngName":"al-qadr","arabicName":"al-qadr","engTranlated":"The Majesty"},
{ "num" :  98, "EngName":"al-Bayyinah","arabicName":"al-bayyinah","engTranlated":"The Proof"},
{ "num" :  99, "EngName":"Az-Zalzala","arabicName":"Az-Zalzala","engTranlated":"The Shaking"},
{ "num" :  100, "EngName":"al- Adiyat","arabicName":"al- aadiyaat","engTranlated":"The Assaulters"},
{ "num" :  101, "EngName":"al-Qari ah","arabicName":"al-qaari ah","engTranlated":"The Terrible Calamity"},
{ "num" :  102, "EngName":"at-Takathur","arabicName":"at-takaathur","engTranlated":"Worldly Gain"},
{ "num" :  103, "EngName":"al- Asr","arabicName":"al- asr","engTranlated":"Time"},
{ "num" :  104, "EngName":"al-Humazah","arabicName":"al-humazah","engTranlated":"The Slanderer"},
{ "num" :  105, "EngName":"al-Fil","arabicName":"al-feel","engTranlated":"The Elephant"},
{ "num" :  106, "EngName":"al-Quraish","arabicName":"al-quraish","engTranlated":"The Quraish"},
{ "num" :  107, "EngName":"al-Ma un","arabicName":"al-maa oon","engTranlated":"The Daily Necessaries"},
{ "num" :  108, "EngName":"al-Kauthar","arabicName":"al-kauthar","engTranlated":"Abundance"},
{ "num" :  109, "EngName":"al-Kafirun","arabicName":"al-kaafiroon","engTranlated":"The Unbelievers"},
{ "num" :  110, "EngName":"an-Nasr","arabicName":"an-naSr","engTranlated":"The Help"},
{ "num" :  111, "EngName":"Al-Masad","arabicName":"Al-Masad","engTranlated":"The Palm Fibre"},
{ "num" :  112, "EngName":"al-Ikhlas","arabicName":"al-ikhlaaS","engTranlated":"The Unity"},
{ "num" :  113, "EngName":"al-Falaq","arabicName":"al-falaq","engTranlated":"The Daybreak"},
{ "num" :  114, "EngName":"an-Nas","arabicName":"an-naas","engTranlated":"The Men	"}
]								
